use_frameworks!

platform :ios, '9.0'

target 'YBImageBrowserTool_Example' do
  pod 'YBImageBrowserTool', :path => '../'

  target 'YBImageBrowserTool_Tests' do
    inherit! :search_paths

    
  end
end
